--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/fernanACM/WorldCommandBlocker
build-by-default: true
branches:
- PM4
projects:
  WorldCommandBlocker:
    path: ""
    icon: icon-wcb.png
    lint:
      phpstan: false
...
