name: WorldCommandBlocker
main: fernanACM\WorldCommandBlocker\Loader
version: 1.0.0
api: 4.0.0
author: fernanACM
description: Block commands by worlds with WorldCommandBlocker, only for PocketMine-MP 4.0 servers
website: https://github.com/fernanACM